spring:
  application:
    name: city-tour

  datasource:
    url: jdbc:postgresql://localhost:5432/city_tour
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true