CREATE TABLE guides
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR(120) NOT NULL CHECK (char_length(full_name) >= 3),
    phone            VARCHAR(20)  NOT NULL UNIQUE,
    experience_years INTEGER      NOT NULL CHECK (experience_years >= 0),
    active           BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE guide_languages
(
    guide_id BIGINT     NOT NULL,
    language VARCHAR(2) NOT NULL CHECK (language IN ('UZ', 'RU', 'EN', 'TR')),

    PRIMARY KEY (guide_id, language),

    CONSTRAINT fk_guide_languages_guide
        FOREIGN KEY (guide_id)
            REFERENCES guides (id)
            ON DELETE CASCADE
);

CREATE TABLE attractions
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255)   NOT NULL UNIQUE,
    address   VARCHAR(255),
    latitude  NUMERIC(10, 7) NOT NULL CHECK (latitude BETWEEN 37.0 AND 46.0),
    longitude NUMERIC(10, 7) NOT NULL CHECK (longitude BETWEEN 55.0 AND 74.0),
    category  VARCHAR(20)    NOT NULL CHECK (category IN (
                                                          'MUSEUM',
                                                          'PARK',
                                                          'MONUMENT',
                                                          'MOSQUE',
                                                          'BAZAAR'
        )),
    entry_fee NUMERIC(12, 2) NOT NULL CHECK (entry_fee >= 0)
);

CREATE TABLE tours
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255)   NOT NULL,
    guide_id       BIGINT         NOT NULL,
    start_time     TIMESTAMP      NOT NULL,
    end_time       TIMESTAMP      NOT NULL CHECK (end_time > start_time),
    max_seats      INTEGER        NOT NULL CHECK (max_seats BETWEEN 1 AND 50),
    price_per_seat NUMERIC(12, 2) NOT NULL CHECK (price_per_seat > 0),
    status         VARCHAR(20)    NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),

    CONSTRAINT fk_tours_guide
        FOREIGN KEY (guide_id)
            REFERENCES guides (id)
);

CREATE TABLE tour_stops
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id       BIGINT  NOT NULL,
    attraction_id BIGINT  NOT NULL,
    visit_order   INTEGER NOT NULL CHECK (visit_order >= 1),
    stay_minutes  INTEGER NOT NULL CHECK (stay_minutes BETWEEN 5 AND 240),

    CONSTRAINT fk_tour_stops_tour
        FOREIGN KEY (tour_id)
            REFERENCES tours (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_tour_stops_attraction
        FOREIGN KEY (attraction_id)
            REFERENCES attractions (id),

    CONSTRAINT uq_tour_stops_tour_order
        UNIQUE (tour_id, visit_order),

    CONSTRAINT uq_tour_stops_tour_attraction
        UNIQUE (tour_id, attraction_id)
);

CREATE TABLE bookings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id        BIGINT         NOT NULL,
    customer_name  VARCHAR(255)   NOT NULL,
    customer_phone VARCHAR(20)    NOT NULL,
    seats          INTEGER        NOT NULL CHECK (seats BETWEEN 1 AND 10),
    total_price    NUMERIC(12, 2) NOT NULL CHECK (total_price > 0),
    status         VARCHAR(20)    NOT NULL CHECK (status IN ('CONFIRMED', 'CANCELLED')),
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bookings_tour
        FOREIGN KEY (tour_id)
            REFERENCES tours (id)
);